### ISSUE TITLE
Duplicate Example in File

### ISSUE THREAD

**Issue by EShafferPPG** [dotnet/AspNetApiDocs#113]
In the document located here:
ApiDocs/aspnet-core/xml/Microsoft.AspNetCore.Mvc/FromServicesAttribute.xml

The usage example is duplicated, so I am not sure if there should be two examples or just one, but it's duplicated.

**Comment by Rick-Anderson** [comment]
I don't see the duplication for https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromservicesattribute?view=aspnetcore-5.0
