### ISSUE TITLE
Obsolete attribute data doesn't pivot on version

### ISSUE THREAD

**Issue by analogrelay** [dotnet/AspNetApiDocs#115]
See https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.iapplicationlifetime?view=aspnetcore-2.2

This attribute was obsoleted in 3.0, but the obsolete warning shows in the docs in all the version views. If it's going to show in all the views, perhaps it should indicate which version obsoleted it?

![image](https://user-images.githubusercontent.com/7574/56015979-ab087080-5caf-11e9-96e5-04577feff5eb.png)

See https://github.com/aspnet/AspNetCore/issues/8949

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
