### ISSUE TITLE
ApplicationStopping docs reference undefined event

### ISSUE THREAD

**Issue by breyed** [dotnet/AspNetApiDocs#119]
The docs for [IApplicationLifetime.ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime.applicationstopping) say, "Shutdown will block until this event completes." That summary reads as if `ApplicationStopping` is an event that the application can control the duration of based on long it takes for all event handlers to return. However, it's really just a property that returns a cancellation token.

If the application wants to let the application lifetime manager know when stopping is complete, it must do some in some other way. Documentation of or a link to what that way is would be appropriate here.

Note too that `ApplicationStopped` has a similar statement in its docs.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
