### ISSUE TITLE
Unfinished sentences in OptionsServiceCollectionExtensions.Configure (<seealso> not showing up)

### ISSUE THREAD

**Issue by bbarry** [dotnet/AspNetApiDocs#120]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.configure?view=aspnetcore-2.2

contains the string (multiple times) "Note: These are run before all ."

The source lines appear to have <seealso> tags:

    Note: These are run before all <seealso cref="M:Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.PostConfigure``1(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.Action{``0})" />.

from https://github.com/aspnet/ApiDocs/blob/live/aspnet-core/xml/Microsoft.Extensions.DependencyInjection/OptionsServiceCollectionExtensions.xml#L168

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
