### ISSUE TITLE
IActionResult interface

### ISSUE THREAD

**Issue by DrReedo** [dotnet/AspNetApiDocs#124]
Can the documentation please give the full contract for the interface?  It doesn't detail the methods, properties etc. that the interface defines.  This would be very useful in trying to understand how it works.

many thanks

**Comment by ShreyasJejurkar** [comment]
That interface only has one method as you can see here. https://source.dot.net/#Microsoft.AspNetCore.Mvc.Abstractions/IActionResult.cs,4c3b5c8150937c35

And that method is already included in the documentation which is here -> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.iactionresult?view=aspnetcore-6.0
