### ISSUE TITLE
Misleading Description for MvcHtmlString.Create()

### ISSUE THREAD

**Issue by ryanmajidi** [dotnet/AspNetApiDocs#127]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1478) by @vikscool**

The description of the function MvcHtmlString.Create() is misleading as it states that it:

Creates an HTML-encoded string using the specified text value.

But instead, it is decoding an already HTML-encoded string and if you pass an HTML string to it, it simply outputs its HTML.

For eg:
@MvcHtmlString.Create("i am &lt;bold&gt;")
will output an decoded HTML code:

I am Bold

and if we input an simple HTML string like:
@MvcHtmlString.Create("I am <b>bold</b>)
again it is written as a normal HTML code:

I am Bold

instead of i am &lt;bold&gt;

Please fix the description as it confuses to whoever is using it.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
