### ISSUE TITLE
no documentation for GenericHostWebHostBuilderExtensions

### ISSUE THREAD

**Issue by webczat** [dotnet/AspNetApiDocs#139]
It seems there is no documentation for Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.
Also, documentation for Microsoft.Extensions.Hosting.GenericHostExtensions is inaccessible on docs.microsoft.com even though it exists, because it is not displayed in listing of Microsoft.Extensions.Hosting namespace, as the namespace page is displayed from .net platform extensions instead.

**Comment by webczat** [comment]
hmm ok, seems the docs themselves are available, was looking in wrong page, but the comment about inaccessibility of correct namespace listing remains correct. Not quite sure if there is anything else that may be missing by accident or not.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
