### ISSUE TITLE
MovieExists

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetApiDocs#150]
@maketochen commented on [Thu Apr 02 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/254)

Where does MovieExists declare it

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [ASP.NET Core 中的控制器方法和视图](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Thu Apr 02 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/254#issuecomment-607784733)

Hello, @maketochen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
It's all in the tutorial.
