### ISSUE TITLE
Typo in SessionsOptions Class page, for the IOTimeout property description

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetApiDocs#165]
---
**Issue moved from MicrosoftDocs/feedback#3145**
- Please respond to @Kilazur.

---

_From @Kilazur on Tuesday, September 29, 2020 1:39:22 PM_

In the page https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.sessionoptions?view=aspnetcore-3.1, in the IOTimeout property description, we can read the word "**maximim**", which I assume should be "**maximum**".

![image](https://user-images.githubusercontent.com/7058306/94565774-e9119f80-0269-11eb-8dab-dff8f3a62b40.png)

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3145**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, September 29, 2020 1:39:23 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
