### ISSUE TITLE
OpenIdConnect API docs are missing for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetApiDocs#200]
---
**Issue moved from MicrosoftDocs/feedback#3402**
- Please respond to @ryanhofdotgov.

---

_From @ryanhofdotgov on Wednesday, January 20, 2021 6:52:55 PM_

**Describe the bug**
The `Microsoft.AspNetCore.Authentication.OpenIdConnect` namespace is missing from the ASP.NET Core 3.1 documentation, as viewed in the [.NET API browser](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.1).

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.1
2. Search for `OpenIdConnectHandler` (an example of one specific class in the namespace)
3. Result is error message: `No results`

**Expected behavior**
I would expect similar search results/corresponding documentation that I see when changing the ASP.NET version to other versions. When making the same search query for `OpenIdConnectHandler` while specifying 3.0, I get this [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnecthandler?view=aspnetcore-3.0). Similarly, when I specify ASP.NET Core 5.0, I get this [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnecthandler?view=aspnetcore-5.0), respectively.

For ASP.NET 3.1, I've verified that the [corresponding source code for OpenIdConnectHandler exists](https://github.com/dotnet/aspnetcore/blob/1b1646a5a6b6898b0433fd3b7f4f34fbd4b28ef7/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L30).

**Desktop:**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 87

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3402**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, January 20, 2021 6:52:57 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3402**
- Please respond to @gewarren.

---

_From @gewarren on Saturday, February 13, 2021 1:35:26 AM_

@jamesnk What is your take on this?

**Comment by JamesNK** [comment]
Seems like a bug. OpenIdConnectHandler is available for .NET 5 and .NET Core 3, but not .NET Core 3.1. It should be.

**Comment by gewarren** [comment]
@v-alje Is this something you can fix?

**Comment by v-alje** [comment]
This has been fixed with https://github.com/dotnet/AspNetApiDocs/pull/207
