### ISSUE TITLE
CookieAuthenticationOptions.ExpireTimeSpan does influence the cookie's max-age

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/AspNetApiDocs#226]
The document for `CookieAuthenticationOptions.ExpireTimeSpan` says that it's separate from `CookieOptions.Expires`, which is true, but I think it should mention that if `AuthenticationProperties.IsPersistent` is true and you provide a value for `CookieAuthenticationOptions.ExpireTimeSpan`, then the Expires/Max-Age of the cookie sent to the browser will be that of the `CookieAuthenticationOptions.ExpireTimeSpan` value. This is what I'm seeing with .NET 6.0.3.

So, it's true that they're separate things, but ExpireTimeSpan will set/influence the cookie's max-age value.

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.expiretimespan](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.expiretimespan)

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
