### ISSUE TITLE
Invalid link description in ApiControllerAttribute documentation

### ISSUE THREAD

**Issue by KeterSCP** [dotnet/AspNetApiDocs#230]
**Issue description**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apicontrollerattribute?view=aspnetcore-6.0#remarks has link name `Cookie policy middleware`, however, it actually leads to https://docs.microsoft.com/en-us/aspnet/core/web-api/#apicontroller-attribute.

~~I couldn't find any corresponding file for this doc to make a PR and also it doesn't have the "quick edit" button, so I suppose it was auto-generated.~~

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by Rick-Anderson** [comment]
>  @Rick-Anderson Does this change need to be made in the source code though?

Yes, change needs to be done in the source. The link is correct, it's just the link text that's incorrect.

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetApiDocs/pull/195/files
Copy/paste error when I added that link. 
@KeterSCP  you can edit https://github.com/dotnet/AspNetApiDocs/blob/main/aspnet-core/xml/Microsoft.AspNetCore.Mvc/ApiControllerAttribute.xml

**Comment by KeterSCP** [comment]
I see there are duplicates on line 59 and 61. I suppose only one should be left, so the question is which one?

**Comment by Rick-Anderson** [comment]
I don't see dup's. Questions like this should be asked in the PR and links to the lines, not the raw line number.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
