### ISSUE TITLE
Docs page links to old MSDN Library site

### ISSUE THREAD

**Issue by MV10** [dotnet/AspNetApiDocs#41]
The link for the ClaimsPrincipal property value on ASP.NET Core HttpContext.User is pointing to the .NET Framework on the old MSDN Library rather than the .NET Core docs. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.user?view=aspnetcore-2.0#Microsoft_AspNetCore_Http_HttpContext_User

The link points to the URL below:

https://msdn.microsoft.com/en-us/library/system.security.claims.claimsprincipal(v=vs.110).aspx

The correct Framework version on the new docs site:

https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal?view=netframework-4.7

The .NET Core version on the new docs site:

https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal?view=netcore-2.0

(I'm assuming once the link is fixed to point to the new docs site, the "view" parameter from the original page is somehow added to the target URL? Haven't really looked at your docs markup...)

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
