### ISSUE TITLE
Include MemoryCacheOptions.SizeLimit Property unit of measure

### ISSUE THREAD

**Issue by ketrex2** [dotnet/AspNetApiDocs#43]
The [MemoryCacheOptions.SizeLimit Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheoptions.sizelimit?view=aspnetcore-2.0) page includes a description of the property as "Gets or sets the maximum size of the cache."

This provides no information as to what the property represents as far as unit size. Consider including the unit of measure (bytes, kilobytes, etc) for accuracy.

I would do a PR for this, but I can't find a size specified in the Caching repo either. It appears to be bytes, but I cannot confirm.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
