### ISSUE TITLE
ConfigurationExtensions.GetConnectionString method

### ISSUE THREAD

**Issue by Emrahdi** [dotnet/AspNetApiDocs#49]
Hi,
This method has a description as "_Shorthand for GetSection("ConnectionStrings")[name]_".

So this method expects a configuration in appsettings.json file with the given key "ConnectionStrings".
There is no problem so far. But "ConnectionStrings" key has only the value, connection string itself as a string type. Limitation of this usage leads confusion for me.

I want to define the other properties of the connection easily, not only the connection string itself.

Limited Usage
 "ConnectionStrings": {
    "NorthWindConnection": "server=****; user=***; password=****; database=NorthWindDatabase; pooling=true; Max Pool Size=100; Min Pool Size=8",
    }

Flexible Usage
  "ConnectionStrings": [
    {
      "Code": "MyDbContext",
      "ProviderName": "System.Data.SqlClient",
      "ConnectionString": "server=****; user=***; password=****; database=NorthWindDatabase; pooling=true; Max Pool Size=100; Min Pool Size=8",
      "CommandTimeOut":5,
    }
  ]

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
