### ISSUE TITLE
Unexpected Behavior for Logger Formatting string 

### ISSUE THREAD

**Issue by FireAndIce68** [dotnet/AspNetApiDocs#50]
Bug / Unexpected Behaviour in ILogger

The following behavior is different to string.Format and this difference should either be documented or fixed. 

The following code following behaves  unexpectedly:
_logger.LogWarning("TEST {0} repeats {0}", 1); => Expect: TEST 1 repeats 1 but get IndexOutOfRange exception.
_logger.LogWarning("TEST {0} repeats {0}", 1, 2); => Expect: TEST 1 repeats 1 but get TEST 1 repeats 2

This should be fixed or documented

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
