### ISSUE TITLE
cref links not showing up

### ISSUE THREAD

**Issue by user135711** [dotnet/AspNetApiDocs#52]
The cref links are not appearing on this [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.cookie?view=aspnetcore-2.0). The cookie property crefs from this direct github [link](https://github.com/aspnet/ApiDocs/blob/live/api/xml/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.xml)

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
