### ISSUE TITLE
Code displaying as plain text

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/AspNetApiDocs#62]
On this page, and everything else in the Microsoft.Extensions.Logging API, the code examples are displaying as normal text.

https://github.com/aspnet/ApiDocs/blob/live/api/xml/Microsoft.Extensions.Logging/LoggerExtensions.xml

![image](https://user-images.githubusercontent.com/4837132/39916660-092d2cba-5503-11e8-91b8-0b403b86f036.png)

**Comment by programistka** [comment]
Is this issue still relevant? The URL returns 404.

**Comment by ChrisMaddock** [comment]
Yep - here’s the actual page:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logtrace

**Comment by programistka** [comment]
Hi @ChrisMaddock I have made a few changes in relation to the code formatting but the built was failed and I'm not sure how it is related to my changes. Do you maybe have any ideas why? Here is my PR - [https://github.com/aspnet/ApiDocs/pull/84](url)
