### ISSUE TITLE
Incomplete sentences in CookieAuthenticationOptions remarks

### ISSUE THREAD

**Issue by duncanawoods** [dotnet/AspNetApiDocs#73]
It looks like property names from the class should be appearing in the text but they are missing making the remarks unintelligible e.g.

> determines if the browser should allow the cookie to be attached to same-site or cross-site requests.

and

> determines if the browser should allow the cookie to be accessed by client-side javascript.

and 

> is currently ignored. Use ExpireTimeSpan to control lifetime of cookie authentication.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
