### ISSUE TITLE
Identify NuGet package in API ref

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetApiDocs#76]
Currently we show the DLL which usually has the same name format as the package - but not always.

[UseHsts](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.hstsbuilderextensions.usehsts?view=aspnetcore-2.1#Microsoft_AspNetCore_Builder_HstsBuilderExtensions_UseHsts_Microsoft_AspNetCore_Builder_IApplicationBuilder_) 
Assembly: Microsoft.AspNetCore.HttpsPolicy.dll

For discussion, see https://github.com/aspnet/Docs/pull/7879

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
